// Fill out your copyright notice in the Description page of Project Settings.


#include "Item.h"
#include "Components/SphereComponent.h"
#include "Particles/ParticleSystemComponent.h"
#include "Kismet/GameplayStatics.h"
#include "Sound/SoundCue.h"
#include "Main.h"
#include "Enemy.h"

// Sets default values
AItem::AItem()
	: bCanRotate{ false }, RotationRate{ 45.f } {

 	// Set this actor to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;

	CollisionVolume = CreateDefaultSubobject<USphereComponent>(TEXT("CollisionVolume"));
	RootComponent = CollisionVolume;

	Mesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("Mesh"));
	Mesh->SetupAttachment(GetRootComponent());

	IdleParticlesComponent = CreateDefaultSubobject<UParticleSystemComponent>(TEXT("IdleParticlesComponent"));
	IdleParticlesComponent->SetupAttachment(GetRootComponent());
}

// Called when the game starts or when spawned
void AItem::BeginPlay()
{
	Super::BeginPlay();
	
	CollisionVolume->OnComponentBeginOverlap.AddDynamic(this, &AItem::OnOverlapBegin);
	CollisionVolume->OnComponentEndOverlap.AddDynamic(this, &AItem::OnOverlapEnd);
}

// Called every frame
void AItem::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);

	if (bCanRotate) {
		FRotator Rotation = GetActorRotation();
		Rotation.Yaw += DeltaTime * RotationRate;
		SetActorRotation(Rotation);
	}
}

void AItem::OnOverlapBegin(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult) {

}

void AItem::OnOverlapEnd(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex) {
	//UE_LOG(LogTemp, Warning, TEXT("OnOverlapEnd Called"));
}

AMain* AItem::GetValidCharacter(AActor* OtherActor) {
	if (OtherActor) {
		AMain* Main{ Cast<AMain>(OtherActor) };
		if (Main) {
			return Main;
		}
	}

	return nullptr;
}

AEnemy* AItem::GetValidEnemy(AActor* OtherActor) {
	if (OtherActor) {
		AEnemy* Enemy{ Cast<AEnemy>(OtherActor) };
		if (Enemy) {
			return Enemy;
		}
	}

	return nullptr;
}

void AItem::EmitParticles() {
	// Emit particles
	if (OverlapParticles) {
		UGameplayStatics::SpawnEmitterAtLocation(GetWorld(), OverlapParticles, GetActorLocation(), FRotator(0.f), true);
	}
}

void AItem::PlaySound() {
	// Play sound
	if (OverlapSound) {
		UGameplayStatics::PlaySound2D(this, OverlapSound);
	}
}